Restructuring

diff --git a/admin_tools/dcmd b/admin_tools/dcmd
--- a/admin_tools/dcmd
+++ b/admin_tools/dcmd
@@ -15,6 +15,8 @@
 
 OPTSTRING="g:r:u:qsp:f:o:dm:"
 USER=$(whoami)
+GROUP=
+REG=
 QUIET=false
 SIMUL=false
 MACHINES=../machines.list
@@ -27,7 +29,7 @@ CLIENT=ssh
 ADDARGS="-C"
 
 dcmd_loadLibs(){
-	if type clog > /dev/null; then
+	if type clog > /dev/null 2>&1; then
 		echo "[dcmd_loadLibs()]" Logging function exists in your environment
 		echo "	" will choose that one
 		[ ! -x $BASH_LIB/aa_term_colors.sh ] && {
@@ -36,12 +38,12 @@ dcmd_loadLibs(){
 		}
 	elif [ -x $BASH_LIB/aa_term_colors.sh -a -x $BASH_LIB/logger.sh ]; then
 		. $BASH_LIB/aa_term_colors.sh || {
-			echo "[dcmd_loadlibs()]" Could not properly source aa_term_colors.sh
+			echo "[dcmd_loadLibs()]" Could not properly source aa_term_colors.sh
 			return 1
 		}
 
 		. $BASH_LIB/logger.sh || {
-			echo "[dcmd_loadlibs()]" Could not properly source logger.sh
+			echo "[dcmd_loadLibs()]" Could not properly source logger.sh
 			return 1
 		}
 	else
@@ -58,20 +60,18 @@ dcmd_loadLibs(){
 
 dcmd_init(){
 	local temp=()
+	local dir=0
 
 	if [ -n "$REG" ]; then
 		mapfile temp < <(grep -E "$REG" $MACHINES)
 	elif [ -n "$GROUP" ]; then
 		mapfile temp < <(grep -E "$GROUP" $MACHINES)
 	elif [ -n "$DIRECT" ]; then
-		local oldifs="$IFS"
-		IFS=","
-		set $DIRECT
-		for ((i=0;i<$#;i++)); do
-			temp[i]=${!i}
+		for i in $(echo "$DIRECT" | tr "," " "); do
+			echo ${i}
+			temp[$dir]=${i}
+			((dir++))
 		done
-		IFS="$oldifs"
-		set --
 	else
 		mapfile temp < <(grep '^[^#]' $MACHINES)
 	fi
@@ -91,7 +91,7 @@ dcmd_init(){
 }
 
 help(){
-	cat <<EOF
+	clog 2 <<EOF
 $0 	[ -g <group> | -r <regex> | -m <regex> ] 
     [ -u <user> ] 
     [ -f <machinefile> ]
@@ -137,11 +137,7 @@ dcmd_parseArgs(){
 	while getopts $OPTSTRING current; do
 		case $current in
 			(g) GROUP="$OPTARG";;
-			(r) REG="$OPTARG"
-				[ -z "$REG" ] && {
-					clog 2 "[dcmd_parseArgs()]" Please provide an REGEX!
-					return 1
-				} ;;
+			(r) REG="$OPTARG";;
 			(u) USER="$OPTARG";;
 			(q) QUIET=true;;
 			(p) PORT=$OPTARG;;
@@ -161,8 +157,9 @@ dcmd_parseArgs(){
 						return 1
 					}
 				} ;;
-			(d) DRY="true";;
+			(d) DEBUG="true";;
 			(m) DIRECT="$OPTARG";;
+
 			(*) clog 1 "[dcmd_parseArgs()]" Invalid option flag
 				return 1;;
 		esac
@@ -218,15 +215,8 @@ dcmd_sendCmd(){
 dcmd_debug(){
 	echo G: $GROUP && echo R: $REG && echo U: $USER && echo Q: $QUIET
 	echo P: $PORT && echo S: $SIMUL && echo F: $MACHINES 
-	echo Dest: $DEST
-
-	for ((j=0; j<${#SOURCE[*]}; j++)); do
-		echo FILE: ${SOURCE[j]}
-		for ((i=0; i<${#MAC[*]}; i++)); do
-			echo ${MAC[i]} " " ${IP[i]} " " ${NAME[i]}
-			echo $CLIENT $ADDARGS -p $PORT ${USER}@${NAME[i]} "$COMMAND"
-		done
-	done
+	echo D: $DEBUG
+	echo Direct: $DIRECT
 
 	return 0
 }
@@ -242,7 +232,7 @@ main(){
 		return 1
 	}
 
-	dcmd_parseArgs || {
+	dcmd_parseArgs $@ || {
 		clog 1 "[main()]" Could not parse Arguments!
 		return 1
 	}
@@ -265,4 +255,4 @@ main(){
 	return 0
 }
 
-main && exit 0 || exit 1
+main $@ && exit 0 || exit 1
diff --git a/admin_tools/dcopy b/admin_tools/dcopy
--- a/admin_tools/dcopy
+++ b/admin_tools/dcopy
@@ -21,10 +21,9 @@ DIRECT=""
 USER=$(whoami)
 PORT=22
 CLIENT=scp
-ADDARGS="-C"
 
 help(){
-	cat <<EOF
+	clog 2 <<EOF
 $0 	[ -g <group> | -r <regex> | -m <regex> ] 
 		[ -u <user> ] 
 		[ -f <machinefile> | -c <csv-String> ]
@@ -50,25 +49,30 @@ $0 	[ -g <group> | -r <regex> | -m <regex> ]
 	<source files/dirs ...> := The name should be sufficient information
 	<destination file/dir> := same as above
 EOF
+
+	return 0
 }
 
-dcopy_init(){
-	local temp=()
-
-	if type clog > /dev/null 
-		echo "[init()]" Logging function exists in your environment
+dcopy_loadLibs(){
+	if type clog > /dev/null 2>&1; then
+		echo "[dcopy_loadLibs()]" Logging function exists in your environment
 		echo "	" will choose that one
-	elif [ -x $BASH_LIB/functions/aa_term_colors.sh -a -x $BASH_LIB/functions/logger.sh ]; then
-		. $BASH_LIB/functions/aa_term_colors.sh || {
-			echo "[init()]" Could not properly souce aa_term_colors.sh
+		[ ! -x $BASH_LIB/aa_term_colors.sh ] && {
+			echo "[dcopy_loadLibs()]" "Missing file for term colors!"
+			return 1
+		}
+	elif [ -x $BASH_LIB/aa_term_colors.sh -a -x $BASH_LIB/logger.sh ]; then
+		. $BASH_LIB/aa_term_colors.sh || {
+			echo "[dcopy_loadLibs()]" Could not properly source aa_term_colors.sh
 			return 1
 		}
 
-		. $BASH_LIB/functions/logger.sh || {
-			echo "[init()]" Could not properly souce logger.sh
+		. $BASH_LIB/logger.sh || {
+			echo "[dcopy_loadLibs()]" Could not properly source logger.sh
 			return 1
 		}
 	else
+		echo "[dcopy_loadLibs()]" Creating dummy logging function 
 		function clog(){
 			shift
 			echo "$@"
@@ -76,19 +80,22 @@ dcopy_init(){
 		}
 	fi
 
+	return 0
+}
+
+dcopy_init(){
+	local temp=()
+
 	if [ -n "$REG" ]; then
 		mapfile temp < <(grep -E "$REG" $MACHINES)
 	elif [ -n "$GROUP" ]; then
 		mapfile temp < <(grep -E "$GROUP" $MACHINES)
 	elif [ -n "DIRECT" ]; then
-		local oldifs="$IFS"
-		IFS=","
-		set $DIRECT
-		for ((i=0;i<$#;i++)); do
-			temp[i]=${!i}
+		for i in $(echo "$DIRECT" | tr "," " "); do
+			echo ${i}
+			temp[$dir]=${i}
+			((dir++))
 		done
-		IFS="$oldifs"
-		set --
 	else
 		mapfile temp < <(grep '^[^#]' $MACHINES)
 	fi
@@ -119,14 +126,15 @@ dcopy_initAgent(){
 }
 
 dcopy_parseArgs(){
+	if [ "$#" = "0" -o "$1" = "--help" -o "$1" = "-h" ]; then
+		help
+		return 1
+	fi
+
 	while getopts $OPTSTRING current; do
 		case $current in
 			(g) GROUP=$OPTARG;;
-			(r) REG="$OPTARG"
-				[ -z "$REG" ] && {
-					clog 2 "[dcmd_parseArgs()]" Please provide an REGEX!
-					return 1
-				} ;;
+			(r) REG="$OPTARG";;
 			(u) USER=$OPTARG;;
 			(q) QUIET=true;;
 			(p) PORT=$OPTARG;;
@@ -158,37 +166,51 @@ dcopy_parseArgs(){
 ##
 dcopy_sendData(){
 	local source=""
+	local addargs=""
 
 	for ((j=0; j<${#SOURCE[*]}; j++)); do
 		# resetting loop internal data
-		ADDARGS=""
-		source=${SOURCE[j]}
+		addargs="-C"
+		source="${SOURCE[j]}"
 
 		if [ -d "$source" ]; then
-			ADDARGS=$ADDARGS" -r"
+			addargs+=" -r"
 		fi
 	
 		if [ "$QUIET" = "true" ]; then
-			ADDARGS=$ADDARGS" -q" # yeah, i know that i could have put the port, user and host  spec in here...
+			addargs+=" -q" 
 			if [ "$SIMUL" = true ]; then
 				for ((i=0; i<${#MAC[*]}; i++)); do
-					$CLIENT $ADDARGS -f -P $PORT "$source" ${USER}@${NAME[i]}:$DEST 
+					$CLIENT $addargs -f -P $PORT "$source" ${USER}@${NAME[i]}:$DEST || {
+						return 1
+					}
 				done
 			else
 				for ((i=0; i<${#MAC[*]}; i++)); do
-					$CLIENT $ADDARGS -P $PORT "$source" ${USER}@${NAME[i]}:$DEST 
+					$CLIENT $addargs -P $PORT "$source" ${USER}@${NAME[i]}:$DEST || {
+						return 1
+					}
 				done
 			fi 	
 		else
 			if [ "$SIMUL" = true ]; then
-				ADDARGS=$ADDARGS" -q"
+				addargs=$addargs" -q"
 				for ((i=0; i<${#MAC[*]}; i++)); do
-					$CLIENT $ADDARGS -f -P $PORT "$source" ${USER}@${NAME[i]}:$DEST 
+					clog 3 ${NAME[i]}-${IP[i]}: copy ${source} to ${DEST}
+					$CLIENT $addargs -f -P $PORT "$source" ${USER}@${NAME[i]}:$DEST || {
+						clog 1 "[dcopy_sendData()]" Failed! \
+							$CLIENT $addargs -f -P $PORT "$source" ${USER}@${NAME[i]}:$DEST 
+						return 1
+					}
 				done
 			else
 				for ((i=0; i<${#MAC[*]}; i++)); do
 					clog 3 ${NAME[i]}-${IP[i]}: copy ${source} to ${DEST}
-					$CLIENT $ADDARGS -P $PORT "$source" ${USER}@${NAME[i]}:$DEST 
+					$CLIENT $addargs -P $PORT "$source" ${USER}@${NAME[i]}:$DEST || {
+						clog 1 "[dcopy_sendData()]" Failed! \
+							$CLIENT $addargs -P $PORT "$source" ${USER}@${NAME[i]}:$DEST
+						return 1
+					}
 				done
 			fi 	
 		fi
@@ -196,14 +218,21 @@ dcopy_sendData(){
 }
 
 dcopy_debug(){
+	local addargs=""
+
 	echo G: $GROUP && echo R: $REG && echo U: $USER && echo Q: $QUIET
 	echo P: $PORT && echo S: $SIMUL && echo F: $MACHINES && echo Sr: ${SOURCE[*]}
 	echo Dest: $DEST
 
 	for ((j=0; j<${#SOURCE[*]}; j++)); do
+		echo 
 		echo FILE: ${SOURCE[j]}
 		for ((i=0; i<${#MAC[*]}; i++)); do
-			echo $CLIENT $ADDARGS -f -P $PORT "$source" ${USER}@${NAME[i]}:$DEST 
+			if [ -d "${SOURCE[j]}" ]; then
+				addargs=" -r"
+			fi
+			echo Command for Name: ${NAME[i]}
+			echo $CLIENT $addargs -f -P $PORT "${SOURCE[j]}" ${USER}@${NAME[i]}:$DEST 
 			echo ${MAC[i]} " " ${IP[i]} " " ${NAME[i]}
 		done
 	done
@@ -213,8 +242,17 @@ dcopy_debug(){
 
 
 main(){
+	dcopy_loadLibs || {
+		clog 1 "[main()]" Could load libraries!
+		return 1
+	}	
 
-	dcopy_parseArgs || {
+	dcopy_initAgent || {
+		clog 1 "[main()]" Could not initialize ssh agent!
+		return 1
+	}
+
+	dcopy_parseArgs $@ || {
 		clog 1 "[main()]" Could not parse options!
 		return 1
 	}
@@ -224,14 +262,8 @@ main(){
 		return 1
 	}
 
-	dcopy_initAgent || {
-		clog 1 "[main()]" Could not initialize ssh agent!
-		return 1
-	}
-
 	if [ $DEBUG = "true" ]; then
 		dcopy_debug
-		return 0
 	else 	
 		dcopy_sendData || {
 			clog 1 "[main()]" Could not send Data!
@@ -242,4 +274,4 @@ main(){
 	return 0	
 }
 
-main && exit 0 || exit 1
+main $@ && exit 0 || exit 1
diff --git a/admin_tools/dnames b/admin_tools/dnames
--- a/admin_tools/dnames
+++ b/admin_tools/dnames
@@ -5,54 +5,115 @@
 #		auf den angegebenen Regex matchen, zeilenweise aus.
 ##
 
-. $BASH_LIB/aa_term_colors.sh
-
-OPTSTR="f:r:"
+OPTSTR="f:r:c"
+CSV="false"
 REGEX="NTB008[Aa]"
-PC_FILE="../machines.list"
+MACHINES="../machines.list"
 
-usage(){
-	cat << EOF
-$0 [ -r <regex> ] [ -f <alternative machine file> ]
+help(){
+	clog 2 << EOF
+$0 [ -r <regex> ] [ -f <alternative machine file> ] [ -c ]
+	-c := Print out a comma separated list of values
 EOF
+
+	return 
 }
 
-if [[ "$1" = @(--[hH][Ee][lL][pP]|-[hH]) || "$#" = 0 ]]; then
-	log_prompt(){
-		echo -n ""
-	}
-	usage | clog 2
-	exit 0
-fi
+dnames_loadLibs(){
+	if type clog > /dev/null 2>&1; then
+		echo "[dnames_loadLibs()]" Logging function exists in your environment
+		echo "	" will choose that one
+		[ ! -x $BASH_LIB/aa_term_colors.sh ] && {
+			echo "[dnames_loadLibs()]" "Missing file for term colors!"
+			return 1
+		}
+	elif [ -x $BASH_LIB/aa_term_colors.sh -a -x $BASH_LIB/logger.sh ]; then
+		. $BASH_LIB/aa_term_colors.sh || {
+			echo "[dnames_loadLibs()]" Could not properly source aa_term_colors.sh
+			return 1
+		}
 
-while getopts $OPTSTR input; do
-	case $input in
-		(f) PC_FILE=$OPTARG
-			;;
-		(r) REGEX=$OPTARG
-			;;
-		(*)
-			;;
-	esac
-done
+		. $BASH_LIB/logger.sh || {
+			echo "[dnames_loadLibs()]" Could not properly source logger.sh
+			return 1
+		}
+	else
+		echo "[dnames_loadLibs()]" Creating dummy logging function 
+		function clog(){
+			shift
+			echo "$@"
+			return 0
+		}
+	fi
+
+	return 0
+}
+
+dnames_parseArgs(){
+	if [ "$#" = "0" -o "$1" = "--help" -o "$1" = "-h" ]; then
+		help
+		return 1
+	fi
+
+	while getopts $OPTSTR input; do
+		case $input in
+			(f) MACHINES="$OPTARG"
+				[ ! -f "$MACHINES" ] && {
+					clog 1 "[dnames_parseArgs()]" "Invalid filename for machines file!"
+					return 1
+				} ;;
+			(r) REGEX=$OPTARG ;;
+			(c) CSV="true" ;;
+			(*) help; return 1 ;;
+		esac
+	done
+
+	return 0
+}
+
+dnames_printNames(){
+	local temp=()
+
+	mapfile temp < <(grep "$REGEX" "$MACHINES")
+
+	for ((i=0; i<${#temp[*]}; i++)); do
+		set ${temp[i]}
+		if [ "$CSV" = "false" ]; then
+			echo $1
+		else 
+			if [ $i -eq $((${#temp[*]}-1)) ]; then
+				echo -n $1
+			else 
+				echo -n $1","
+			fi
+		fi
+	done
+
+	return 0
+}
 
 
 ##
 # Fills the Array "NAME"
 # with fitting values
 ##
-init(){
-	if [ -n "$REGEX" ]; then
-		mapfile TEMP < <(grep "$REGEX" "$PC_FILE")
-	fi
+main(){
+	dnames_loadLibs || {
+		clog 1 "[main()]" Could not load Libraries!
+		return 1
+	}
 
-	for ((i=0; i<${#TEMP[*]}; i++)); do
-		set ${TEMP[i]}
-		echo $1
-		set --
-	done
-	unset TEMP
+	dnames_parseArgs $@ || {
+		clog 1 "[main()]" Could not parse options!
+		return 1
+	}
+
+	dnames_printNames || { 
+		clog 1 "[main()]" "Could not print names!"
+		return 1
+	}
+
+	return 1
 }
 
-init
-
+main $@ && exit 0 || exit 1
