Restructuring

diff --git a/admin_tools/dcmd b/admin_tools/dcmd
--- a/admin_tools/dcmd
+++ b/admin_tools/dcmd
@@ -1,15 +1,17 @@
 #!/bin/bash
-#------>dcmd<------
-#Autor: Florian Mayer
-#Datum: 7.Sept.2013
 #
-#$0 	[-g <group> | --nreg <regex> | --ipreg <regex>] 
+# Autor: Florian Mayer
+# Datum: 7.Sept.2013
+# Depends: shellyCode
+#
+# $0 	[-g <group> | --nreg <regex> | --ipreg <regex>] 
 #	[ -u <user> ] 
 #	[ -s ] 
 #	[ -p <portnumber> ] 
 #	[ --simultaneous ]
 #	<command>
 #
+##
 
 OPTSTRING="g:r:u:qsp:f:o:dm:"
 USER=$(whoami)
@@ -25,9 +27,19 @@ CLIENT=ssh
 ADDARGS="-C"
 
 dcmd_init(){
-	if [ -x $BASH_LIB/functions/aa_term_colors.sh ]; then
+	local temp=()
+
+	if type clog > /dev/null 
+		echo "[init()]" Logging function exists in your environment
+		echo "	" will choose that one
+	elif [ -x $BASH_LIB/functions/aa_term_colors.sh -a -x $BASH_LIB/functions/logger.sh ]; then
 		. $BASH_LIB/functions/aa_term_colors.sh || {
 			echo "[init()]" Could not properly souce aa_term_colors.sh
+			return 1
+		}
+
+		. $BASH_LIB/functions/logger.sh || {
+			echo "[init()]" Could not properly souce logger.sh
 			return 1
 		}
 	else
@@ -39,24 +51,24 @@ dcmd_init(){
 	fi
 
 	if [ -n "$REG" ]; then
-		mapfile TEMP < <(grep -E "$REG" $MACHINES)
+		mapfile temp < <(grep -E "$REG" $MACHINES)
 	elif [ -n "$GROUP" ]; then
-		mapfile TEMP < <(grep -E "$GROUP" $MACHINES)
+		mapfile temp < <(grep -E "$GROUP" $MACHINES)
 	elif [ -n "DIRECT" ]; then
 		local oldifs="$IFS"
 		IFS=","
 		set $DIRECT
 		for ((i=0;i<$#;i++)); do
-			TEMP[i]=${!i}
+			temp[i]=${!i}
 		done
 		IFS="$oldifs"
 		set --
 	else
-		mapfile TEMP < <(grep '^[^#]' $MACHINES)
+		mapfile temp < <(grep '^[^#]' $MACHINES)
 	fi
 
-	for ((i=0; i<${#TEMP[*]}; i++)); do
-		set ${TEMP[i]}
+	for ((i=0; i<${#temp[*]}; i++)); do
+		set ${temp[i]}
 		NAME[i]=$1
 		MAC[i]=$2
 		if [ -z "$3" ]; then
@@ -65,7 +77,6 @@ dcmd_init(){
 			IP[i]=$3
 		fi
 	done
-	unset TEMP
 
 	return 0
 }
@@ -186,18 +197,20 @@ dcmd_sendCmd(){
 	return 0
 }
 
-##
-# For debugging use
-##
-print_opts(){
+dcmd_debug(){
 	echo G: $GROUP && echo R: $REG && echo U: $USER && echo Q: $QUIET
-	echo P: $PORT && echo S: $SIMUL && echo C: $COMMAND && echo F: $MACHINES
-}
+	echo P: $PORT && echo S: $SIMUL && echo F: $MACHINES 
+	echo Dest: $DEST
 
-print_arrays(){
-	for ((i=0; i<${#MAC[*]}; i++)); do
-		echo ${MAC[i]} " " ${IP[i]} " " ${NAME[i]}
+	for ((j=0; j<${#SOURCE[*]}; j++)); do
+		echo FILE: ${SOURCE[j]}
+		for ((i=0; i<${#MAC[*]}; i++)); do
+			echo ${MAC[i]} " " ${IP[i]} " " ${NAME[i]}
+			echo $CLIENT $ADDARGS -p $PORT ${USER}@${NAME[i]} "$COMMAND"
+		done
 	done
+
+	return 0
 }
 
 main(){
@@ -216,10 +229,15 @@ main(){
 		return 1
 	}
 
-	dcmd_sendCmd || {
-		clog 1 "[main()]" "Error while sending commands!"
-		return 1
-	}
+	if [ $DEBUG = "true" ]; then
+		dcmd_debug
+		return 0
+	else 
+		dcmd_sendCmd || {
+			clog 1 "[main()]" "Error while sending commands!"
+			return 1
+		}
+	fi
 
 	return 0
 }
diff --git a/admin_tools/dcopy b/admin_tools/dcopy
--- a/admin_tools/dcopy
+++ b/admin_tools/dcopy
@@ -11,18 +11,15 @@
 #	<command>
 #
 
-. $BASH_LIB/functions/aa_term_colors.sh
-
-
-OPTSTRING="g:r:u:qsp:f:dm:"
-USER=$(whoami)
-QUIET=false
-SIMUL=false
+OPTSTRING="g:r:u:qsp:f:dc:"
 MACHINES=$REPO/data/machines.list
-PORT=22
-DRY=false
+SIMUL=false
+DEBUG=false
+QUIET=false
 DIRECT=""
-
+# SSH related
+USER=$(whoami)
+PORT=22
 CLIENT=scp
 ADDARGS="-C"
 
@@ -30,7 +27,7 @@ help(){
 	cat <<EOF
 $0 	[ -g <group> | -r <regex> | -m <regex> ] 
 		[ -u <user> ] 
-		[ -f <machinefile> ]
+		[ -f <machinefile> | -c <csv-String> ]
 		[ -q ] 
 		[ -p <portnumber> ] 
 		[ -s ]
@@ -42,73 +39,62 @@ $0 	[ -g <group> | -r <regex> | -m <regex> ]
 	<regex> := regex for computernames or ip addresses to match
 	<user> := defines the user to connect to
 	<machinefile> := the file to read machine names and mac addersses from
+	<csv-String> := Specifies the computers manually
 	q := silent output if set
 	p := defines the portnumber the ssh command should use
 	s := specifies whether the commands should be run 
 				all at the same time. There is no output for
 				the simultaneous mode!
-	d := specifies whether there should be a dry run. 
+	d := specifies whether the script should run in dry mode (debug) 
+		no changes will be made
 	<source files/dirs ...> := The name should be sufficient information
 	<destination file/dir> := same as above
 EOF
 }
 
-if [[ "$1" = @(--[hH][Ee][lL][pP]|-[hH]) || "$#" = 0 ]]; then
-	log_prompt(){
-		echo -n ""
-	}
-	help | clog 2
-	exit 0
-fi
+dcopy_init(){
+	local temp=()
 
-if [ "$(ssh-add -L)" = "The agent has no identities." ]; then
-	ssh-add
-fi
+	if type clog > /dev/null 
+		echo "[init()]" Logging function exists in your environment
+		echo "	" will choose that one
+	elif [ -x $BASH_LIB/functions/aa_term_colors.sh -a -x $BASH_LIB/functions/logger.sh ]; then
+		. $BASH_LIB/functions/aa_term_colors.sh || {
+			echo "[init()]" Could not properly souce aa_term_colors.sh
+			return 1
+		}
 
-while getopts $OPTSTRING current; do
-	case $current in
-		(g) GROUP=$OPTARG;;
-		(r) REG="$OPTARG";;
-		(u) USER=$OPTARG;;
-		(q) QUIET=true;;
-		(p) PORT=$OPTARG;;
-		(s) SIMUL=true;;
-		(f) MACHINES="$OPTARG";;
-		(d) DRY="true";;
-		(m) DIRECT="$OPTARG";;
-	esac
-done
-shift $((OPTIND-1)) 
-for ((i=1; i<$#; i++)); do
-	SOURCE[i-1]="${!i}"
-done
-DEST="${!#}"
+		. $BASH_LIB/functions/logger.sh || {
+			echo "[init()]" Could not properly souce logger.sh
+			return 1
+		}
+	else
+		function clog(){
+			shift
+			echo "$@"
+			return 0
+		}
+	fi
 
-
-##
-# Fills the Arrays "MAC", "IP" and "NAME"
-# with fitting values
-##
-init(){
 	if [ -n "$REG" ]; then
-		mapfile TEMP < <(grep "$REG" $MACHINES)
+		mapfile temp < <(grep -E "$REG" $MACHINES)
 	elif [ -n "$GROUP" ]; then
-		mapfile TEMP < <(grep "$GROUP" $MACHINES)
+		mapfile temp < <(grep -E "$GROUP" $MACHINES)
 	elif [ -n "DIRECT" ]; then
 		local oldifs="$IFS"
 		IFS=","
 		set $DIRECT
 		for ((i=0;i<$#;i++)); do
-			TEMP[i]=${!i}
+			temp[i]=${!i}
 		done
 		IFS="$oldifs"
 		set --
 	else
-		mapfile TEMP < <(grep '^[^#]' $MACHINES)
+		mapfile temp < <(grep '^[^#]' $MACHINES)
 	fi
 
-	for ((i=0; i<${#TEMP[*]}; i++)); do
-		set ${TEMP[i]}
+	for ((i=0; i<${#temp[*]}; i++)); do
+		set ${temp[i]}
 		NAME[i]=$1
 		MAC[i]=$2
 		if [ -z "$3" ]; then
@@ -117,15 +103,61 @@ init(){
 			IP[i]=$3
 		fi
 	done
-	unset TEMP
+
+	return 0
+}
+
+dcopy_initAgent(){
+	if [ "$(ssh-add -L)" = "The agent has no identities." ]; then
+		ssh-add || {
+			clog 2 "[dcmd_initAgent()]" Ssh-add could not be executed properly
+			return 1
+		}
+	fi
+
+	return 0
+}
+
+dcopy_parseArgs(){
+	while getopts $OPTSTRING current; do
+		case $current in
+			(g) GROUP=$OPTARG;;
+			(r) REG="$OPTARG"
+				[ -z "$REG" ] && {
+					clog 2 "[dcmd_parseArgs()]" Please provide an REGEX!
+					return 1
+				} ;;
+			(u) USER=$OPTARG;;
+			(q) QUIET=true;;
+			(p) PORT=$OPTARG;;
+			(s) SIMUL=true;;
+			(f) MACHINES="$OPTARG"
+				[ ! -f "$MACHINES" ] && {
+					clog 1 "[dcmd_parseArgs()]" "Invalid filename for machines file!"
+					return 1
+				} ;;
+			(d) DEBUG="true";;
+			(c) DIRECT="$OPTARG";;
+			(*) clog 1 "[dcmd_parseArgs()]" Invalid option flag
+				return 1;;
+		esac
+	done
+
+	shift $((OPTIND-1)) 
+	for ((i=1; i<$#; i++)); do
+		SOURCE[i-1]="${!i}"
+	done
+	DEST="${!#}"
+
+	return 0
 }
 
 ##
 # Sends the specified files/dirs to the initialized hosts
 # if the given path is a directory scp -r is used!
 ##
-send_data(){
-	local source=
+dcopy_sendData(){
+	local source=""
 
 	for ((j=0; j<${#SOURCE[*]}; j++)); do
 		# resetting loop internal data
@@ -149,7 +181,7 @@ send_data(){
 			fi 	
 		else
 			if [ "$SIMUL" = true ]; then
-				ADDARGS=$ADDARGS" -q" #always quiet
+				ADDARGS=$ADDARGS" -q"
 				for ((i=0; i<${#MAC[*]}; i++)); do
 					$CLIENT $ADDARGS -f -P $PORT "$source" ${USER}@${NAME[i]}:$DEST 
 				done
@@ -163,26 +195,51 @@ send_data(){
 	done
 }
 
-##
-# For dry run use
-##
-print_opts(){
+dcopy_debug(){
 	echo G: $GROUP && echo R: $REG && echo U: $USER && echo Q: $QUIET
-	echo P: $PORT && echo S: $SIMUL && echo F: $MACHINES && echo Sr: ${SOURCE[0]}
+	echo P: $PORT && echo S: $SIMUL && echo F: $MACHINES && echo Sr: ${SOURCE[*]}
 	echo Dest: $DEST
-}
 
-print_arrays(){
-	for ((i=0; i<${#MAC[*]}; i++)); do
-		echo ${MAC[i]} " " ${IP[i]} " " ${NAME[i]}
+	for ((j=0; j<${#SOURCE[*]}; j++)); do
+		echo FILE: ${SOURCE[j]}
+		for ((i=0; i<${#MAC[*]}; i++)); do
+			echo $CLIENT $ADDARGS -f -P $PORT "$source" ${USER}@${NAME[i]}:$DEST 
+			echo ${MAC[i]} " " ${IP[i]} " " ${NAME[i]}
+		done
 	done
+
+	return 0
 }
 
-init
 
-if [ $DRY = "false" ]; then
-	send_data
-else
-	print_opts
-	print_arrays
-fi
+main(){
+
+	dcopy_parseArgs || {
+		clog 1 "[main()]" Could not parse options!
+		return 1
+	}
+
+	dcopy_init || {
+		clog 1 "[main()]" Could not initialize dcopy!
+		return 1
+	}
+
+	dcopy_initAgent || {
+		clog 1 "[main()]" Could not initialize ssh agent!
+		return 1
+	}
+
+	if [ $DEBUG = "true" ]; then
+		dcopy_debug
+		return 0
+	else 	
+		dcopy_sendData || {
+			clog 1 "[main()]" Could not send Data!
+			return 1
+		}
+	fi
+
+	return 0	
+}
+
+main && exit 0 || exit 1
